export const ALLIANCES: Record<string, string> = {
  // SkyTeam
  "Air France": "SkyTeam",
  "KLM": "SkyTeam",
  "Delta": "SkyTeam",
  "Korean Air": "SkyTeam",
  "China Southern": "SkyTeam",
  "Aeromexico": "SkyTeam",
  "Air Europa": "SkyTeam",
  "ITA Airways": "SkyTeam",
  "Kenya Airways": "SkyTeam",
  "ASKY Airlines": "SkyTeam",
  // Star Alliance
  "Lufthansa": "Star Alliance",
  "United": "Star Alliance",
  "Air Canada": "Star Alliance",
  "Singapore Airlines": "Star Alliance",
  "Turkish Airlines": "Star Alliance",
  "Ethiopian Airlines": "Star Alliance",
  "South African Airways": "Star Alliance",
  "Swiss": "Star Alliance",
  "EgyptAir": "Star Alliance",
  "TAP Air Portugal": "Star Alliance",
  // Oneworld
  "British Airways": "Oneworld",
  "American Airlines": "Oneworld",
  "Qatar Airways": "Oneworld",
  "Finnair": "Oneworld",
  "Iberia": "Oneworld",
  "Royal Air Maroc": "Oneworld",
  "Malaysia Airlines": "Oneworld",
  // Independent
  "Emirates": "Independent",
  "Etihad": "Independent",
  "RwandAir": "Independent",
  "Air Senegal": "Independent",
};
