// lib/zones.ts

export type Zone =
  | "AFRICA_WEST"
  | "AFRICA_NORTH"
  | "AFRICA_EAST"
  | "AFRICA_SOUTH"
  | "EUROPE"
  | "NORTH_AMERICA"
  | "MIDDLE_EAST"
  | "ASIA"
  | "SOUTH_AMERICA";

const ZONE_MAP: Record<string, Zone> = {
  // ── Africa North ──────────────────────────────────────────────────────────
  // Morocco
  CMN: "AFRICA_NORTH", RAK: "AFRICA_NORTH", FEZ: "AFRICA_NORTH",
  ORN: "AFRICA_NORTH", TNG: "AFRICA_NORTH", OUD: "AFRICA_NORTH",
  NDR: "AFRICA_NORTH", AHU: "AFRICA_NORTH", SMW: "AFRICA_NORTH",
  EUN: "AFRICA_NORTH", TTA: "AFRICA_NORTH", ERH: "AFRICA_NORTH",
  // Tunisia
  TUN: "AFRICA_NORTH", SFA: "AFRICA_NORTH", MIR: "AFRICA_NORTH",
  TOE: "AFRICA_NORTH", TBR: "AFRICA_NORTH", GAF: "AFRICA_NORTH",
  DJE: "AFRICA_NORTH",
  // Algeria
  ALG: "AFRICA_NORTH", ORN: "AFRICA_NORTH", CZL: "AFRICA_NORTH",
  AAE: "AFRICA_NORTH", BJA: "AFRICA_NORTH", GJL: "AFRICA_NORTH",
  TLM: "AFRICA_NORTH", TMR: "AFRICA_NORTH", BSK: "AFRICA_NORTH",
  HME: "AFRICA_NORTH", ELU: "AFRICA_NORTH", GHA: "AFRICA_NORTH",
  TGR: "AFRICA_NORTH", OGX: "AFRICA_NORTH", INZ: "AFRICA_NORTH",
  IAM: "AFRICA_NORTH", AZR: "AFRICA_NORTH", BLJ: "AFRICA_NORTH",
  // Libya
  TIP: "AFRICA_NORTH", BEN: "AFRICA_NORTH", MJI: "AFRICA_NORTH",
  GHT: "AFRICA_NORTH", SEB: "AFRICA_NORTH",
  // Egypt
  CAI: "AFRICA_NORTH", HRG: "AFRICA_NORTH", SSH: "AFRICA_NORTH",
  LXR: "AFRICA_NORTH", ASW: "AFRICA_NORTH", ABU: "AFRICA_NORTH",
  ABS: "AFRICA_NORTH", MYW: "AFRICA_NORTH", RMF: "AFRICA_NORTH",
  // Western Sahara (served via Moroccan airports)
  VIL: "AFRICA_NORTH",

  // ── Africa West ───────────────────────────────────────────────────────────
  // Senegal / Gambia / Guinea-Bissau
  DSS: "AFRICA_WEST", DKR: "AFRICA_WEST", ZIG: "AFRICA_WEST",
  BJL: "AFRICA_WEST", OXB: "AFRICA_WEST",
  // Guinea Conakry / Sierra Leone / Liberia
  CKY: "AFRICA_WEST", FNA: "AFRICA_WEST", MLW: "AFRICA_WEST",
  ROB: "AFRICA_WEST",
  // Ivory Coast / Ghana / Togo / Benin
  ABJ: "AFRICA_WEST", ACC: "AFRICA_WEST", LFW: "AFRICA_WEST",
  COO: "AFRICA_WEST",
  // Nigeria
  LOS: "AFRICA_WEST", ABV: "AFRICA_WEST", PHC: "AFRICA_WEST",
  KAN: "AFRICA_WEST", CBQ: "AFRICA_WEST", BNI: "AFRICA_WEST",
  IBA: "AFRICA_WEST", ILR: "AFRICA_WEST", SKO: "AFRICA_WEST",
  QRW: "AFRICA_WEST", ENU: "AFRICA_WEST", MIU: "AFRICA_WEST",
  // Mali / Burkina Faso / Niger
  BKO: "AFRICA_WEST", OUA: "AFRICA_WEST", NIM: "AFRICA_WEST",
  GAO: "AFRICA_WEST", TOM: "AFRICA_WEST",
  // Mauritania / Cape Verde
  NKC: "AFRICA_WEST", MBR: "AFRICA_WEST",
  SID: "AFRICA_WEST", RAI: "AFRICA_WEST", SAL: "AFRICA_WEST",
  // Chad
  NDJ: "AFRICA_WEST",
  // Cameroon / Equatorial Guinea / Gabon / Congo / DRC (western gateway)
  DLA: "AFRICA_WEST", NSI: "AFRICA_WEST", YAO: "AFRICA_WEST",
  SSG: "AFRICA_WEST", LBV: "AFRICA_WEST", MKU: "AFRICA_WEST",
  BZV: "AFRICA_WEST", PNR: "AFRICA_WEST",

  // ── Africa East (incl. Central Africa) ───────────────────────────────────
  // Ethiopia
  ADD: "AFRICA_EAST", DIR: "AFRICA_EAST", GDQ: "AFRICA_EAST",
  GMB: "AFRICA_EAST", JIM: "AFRICA_EAST", MQX: "AFRICA_EAST",
  // Kenya
  NBO: "AFRICA_EAST", MBA: "AFRICA_EAST", KIS: "AFRICA_EAST",
  WJR: "AFRICA_EAST", EDL: "AFRICA_EAST",
  // Tanzania
  DAR: "AFRICA_EAST", ZNZ: "AFRICA_EAST", JRO: "AFRICA_EAST",
  MWZ: "AFRICA_EAST", ARK: "AFRICA_EAST", MBI: "AFRICA_EAST",
  // Uganda / Rwanda / Burundi
  EBB: "AFRICA_EAST", KGL: "AFRICA_EAST", BJM: "AFRICA_EAST",
  // Somalia / Djibouti
  MGQ: "AFRICA_EAST", DJI: "AFRICA_EAST", BBO: "AFRICA_EAST",
  // South Sudan / Sudan
  JUB: "AFRICA_EAST", KRT: "AFRICA_EAST", PZU: "AFRICA_EAST",
  // Eritrea
  ASM: "AFRICA_EAST",
  // DRC / Central African Republic / South Sudan corridor
  FIH: "AFRICA_EAST", FKI: "AFRICA_EAST", GOM: "AFRICA_EAST",
  MYD: "AFRICA_EAST", BGF: "AFRICA_EAST",
  // Indian Ocean (East Africa grouping)
  SEZ: "AFRICA_EAST", RUN: "AFRICA_EAST", MRU: "AFRICA_SOUTH", // Reunion & Seychelles → east; Mauritius → south
  HAH: "AFRICA_EAST",  // Moroni, Comoros

  // ── Africa South ──────────────────────────────────────────────────────────
  // South Africa
  JNB: "AFRICA_SOUTH", CPT: "AFRICA_SOUTH", DUR: "AFRICA_SOUTH",
  PLZ: "AFRICA_SOUTH", GRJ: "AFRICA_SOUTH", ELS: "AFRICA_SOUTH",
  HLA: "AFRICA_SOUTH", UTN: "AFRICA_SOUTH",
  // Zimbabwe / Zambia / Malawi
  HRE: "AFRICA_SOUTH", BUQ: "AFRICA_SOUTH", VFA: "AFRICA_SOUTH",
  LUN: "AFRICA_SOUTH", LLW: "AFRICA_SOUTH",
  // Mozambique / Angola
  MPM: "AFRICA_SOUTH", BEW: "AFRICA_SOUTH", TET: "AFRICA_SOUTH",
  LAD: "AFRICA_SOUTH", SZA: "AFRICA_SOUTH",
  // Namibia / Botswana / Lesotho / Swaziland
  WDH: "AFRICA_SOUTH", GBE: "AFRICA_SOUTH", MSU: "AFRICA_SOUTH",
  MTS: "AFRICA_SOUTH",
  // Madagascar
  TNR: "AFRICA_SOUTH", MJN: "AFRICA_SOUTH", DIE: "AFRICA_SOUTH",
  TMM: "AFRICA_SOUTH", MOQ: "AFRICA_SOUTH",
  // Mauritius (remote south)
  // MRU already placed in EAST above — re-assign to SOUTH for award chart purposes

  // ── Europe ────────────────────────────────────────────────────────────────
  // France
  CDG: "EUROPE", ORY: "EUROPE", LYN: "EUROPE", NCE: "EUROPE",
  MRS: "EUROPE", TLS: "EUROPE", BOD: "EUROPE", NTE: "EUROPE",
  LYS: "EUROPE", MPL: "EUROPE", SXB: "EUROPE", LIL: "EUROPE",
  REU: "EUROPE", RNS: "EUROPE", CLY: "EUROPE", BIQ: "EUROPE",
  CFE: "EUROPE", PGF: "EUROPE", BES: "EUROPE", LRH: "EUROPE",
  // UK & Ireland
  LHR: "EUROPE", LGW: "EUROPE", LCY: "EUROPE", STN: "EUROPE",
  MAN: "EUROPE", EDI: "EUROPE", GLA: "EUROPE", BHX: "EUROPE",
  BRS: "EUROPE", NCL: "EUROPE", LBA: "EUROPE", ABZ: "EUROPE",
  BFS: "EUROPE", ORK: "EUROPE", DUB: "EUROPE", SNN: "EUROPE",
  // Germany
  FRA: "EUROPE", MUC: "EUROPE", DUS: "EUROPE", BER: "EUROPE",
  TXL: "EUROPE", HAM: "EUROPE", STR: "EUROPE", CGN: "EUROPE",
  NUE: "EUROPE", HAJ: "EUROPE", LEJ: "EUROPE", DRS: "EUROPE",
  // Spain
  MAD: "EUROPE", BCN: "EUROPE", PMI: "EUROPE", AGP: "EUROPE",
  VLC: "EUROPE", SVQ: "EUROPE", BIO: "EUROPE", TFN: "EUROPE",
  TFS: "EUROPE", LPA: "EUROPE", FUE: "EUROPE", ACE: "EUROPE",
  SDR: "EUROPE", OVD: "EUROPE", GRX: "EUROPE", ALC: "EUROPE",
  REU: "EUROPE",
  // Portugal
  LIS: "EUROPE", OPO: "EUROPE", FAO: "EUROPE", FNC: "EUROPE",
  PDL: "EUROPE", TER: "EUROPE", HOR: "EUROPE",
  // Italy
  FCO: "EUROPE", MXP: "EUROPE", VCE: "EUROPE", NAP: "EUROPE",
  MIL: "EUROPE", LIN: "EUROPE", BGY: "EUROPE", CTA: "EUROPE",
  PMO: "EUROPE", BRI: "EUROPE", BLQ: "EUROPE", FLR: "EUROPE",
  PSA: "EUROPE", GOA: "EUROPE", CAG: "EUROPE",
  // Netherlands / Belgium / Luxembourg
  AMS: "EUROPE", BRU: "EUROPE", LUX: "EUROPE", EIN: "EUROPE",
  MST: "EUROPE",
  // Switzerland / Austria
  ZRH: "EUROPE", GVA: "EUROPE", BSL: "EUROPE", VIE: "EUROPE",
  SZG: "EUROPE", INN: "EUROPE", LNZ: "EUROPE",
  // Scandinavia
  CPH: "EUROPE", OSL: "EUROPE", ARN: "EUROPE", GOT: "EUROPE",
  BGO: "EUROPE", TRD: "EUROPE", HEL: "EUROPE", TMP: "EUROPE",
  OUL: "EUROPE", REK: "EUROPE",
  // Eastern Europe
  WAW: "EUROPE", KRK: "EUROPE", WRO: "EUROPE", GDN: "EUROPE",
  PRG: "EUROPE", BRQ: "EUROPE", OLO: "EUROPE",
  BUD: "EUROPE", DEB: "EUROPE",
  BUH: "EUROPE", OTP: "EUROPE", CLJ: "EUROPE", TSR: "EUROPE",
  SOF: "EUROPE", VAR: "EUROPE", PDV: "EUROPE",
  KBP: "EUROPE", LWO: "EUROPE", IEV: "EUROPE",
  MSQ: "EUROPE",
  RIG: "EUROPE", TLL: "EUROPE", VNO: "EUROPE",
  // Balkans / South-East Europe
  ATH: "EUROPE", SKG: "EUROPE", HER: "EUROPE", RHO: "EUROPE",
  ZTH: "EUROPE", CFU: "EUROPE",
  BEG: "EUROPE", TIV: "EUROPE", SKP: "EUROPE", TIA: "EUROPE",
  SPU: "EUROPE", ZAG: "EUROPE", DBV: "EUROPE", LJU: "EUROPE",
  // Turkey
  IST: "EUROPE", SAW: "EUROPE", AYT: "EUROPE", ADB: "EUROPE",
  ESB: "EUROPE", DLM: "EUROPE", BJV: "EUROPE",
  // Russia / Caucasus (geographic Europe or served from Europe hubs)
  SVO: "EUROPE", DME: "EUROPE", LED: "EUROPE", KZN: "EUROPE",
  TBS: "EUROPE", EVN: "EUROPE", GYD: "EUROPE",
  // Malta / Cyprus
  MLA: "EUROPE", LCA: "EUROPE", PFO: "EUROPE",

  // ── North America ─────────────────────────────────────────────────────────
  // US East Coast
  JFK: "NORTH_AMERICA", EWR: "NORTH_AMERICA", LGA: "NORTH_AMERICA",
  BOS: "NORTH_AMERICA", MIA: "NORTH_AMERICA", FLL: "NORTH_AMERICA",
  MCO: "NORTH_AMERICA", TPA: "NORTH_AMERICA", PHL: "NORTH_AMERICA",
  DCA: "NORTH_AMERICA", IAD: "NORTH_AMERICA", BWI: "NORTH_AMERICA",
  ATL: "NORTH_AMERICA", CLT: "NORTH_AMERICA", RDU: "NORTH_AMERICA",
  PIT: "NORTH_AMERICA", BUF: "NORTH_AMERICA", BDL: "NORTH_AMERICA",
  RIC: "NORTH_AMERICA", SAV: "NORTH_AMERICA", JAX: "NORTH_AMERICA",
  RSW: "NORTH_AMERICA",
  // US Midwest
  ORD: "NORTH_AMERICA", MDW: "NORTH_AMERICA", DFW: "NORTH_AMERICA",
  DAL: "NORTH_AMERICA", MSY: "NORTH_AMERICA", HOU: "NORTH_AMERICA",
  IAH: "NORTH_AMERICA", MSP: "NORTH_AMERICA", DTW: "NORTH_AMERICA",
  MCI: "NORTH_AMERICA", STL: "NORTH_AMERICA", CVG: "NORTH_AMERICA",
  CLE: "NORTH_AMERICA", CMH: "NORTH_AMERICA", IND: "NORTH_AMERICA",
  MEM: "NORTH_AMERICA", BNA: "NORTH_AMERICA", OMA: "NORTH_AMERICA",
  // US West
  LAX: "NORTH_AMERICA", SFO: "NORTH_AMERICA", SAN: "NORTH_AMERICA",
  SEA: "NORTH_AMERICA", LAS: "NORTH_AMERICA", DEN: "NORTH_AMERICA",
  PDX: "NORTH_AMERICA", PHX: "NORTH_AMERICA", SLC: "NORTH_AMERICA",
  OAK: "NORTH_AMERICA", SJC: "NORTH_AMERICA", SMF: "NORTH_AMERICA",
  ANC: "NORTH_AMERICA", HNL: "NORTH_AMERICA", OGG: "NORTH_AMERICA",
  // Canada
  YYZ: "NORTH_AMERICA", YUL: "NORTH_AMERICA", YVR: "NORTH_AMERICA",
  YYC: "NORTH_AMERICA", YEG: "NORTH_AMERICA", YOW: "NORTH_AMERICA",
  YHZ: "NORTH_AMERICA", YWG: "NORTH_AMERICA", YQB: "NORTH_AMERICA",
  // Mexico
  MEX: "NORTH_AMERICA", CUN: "NORTH_AMERICA", GDL: "NORTH_AMERICA",
  MTY: "NORTH_AMERICA", TIJ: "NORTH_AMERICA", MID: "NORTH_AMERICA",
  BJX: "NORTH_AMERICA", PVR: "NORTH_AMERICA", SJD: "NORTH_AMERICA",
  // Caribbean & Central America
  HAV: "NORTH_AMERICA", SJO: "NORTH_AMERICA", GUA: "NORTH_AMERICA",
  SAP: "NORTH_AMERICA", MGA: "NORTH_AMERICA", PTY: "NORTH_AMERICA",
  SDQ: "NORTH_AMERICA", PUJ: "NORTH_AMERICA", MBJ: "NORTH_AMERICA",
  KIN: "NORTH_AMERICA", NAS: "NORTH_AMERICA", ANU: "NORTH_AMERICA",
  POS: "NORTH_AMERICA", BGI: "NORTH_AMERICA", GND: "NORTH_AMERICA",

  // ── Middle East ───────────────────────────────────────────────────────────
  // Gulf
  DXB: "MIDDLE_EAST", AUH: "MIDDLE_EAST", SHJ: "MIDDLE_EAST",
  DOH: "MIDDLE_EAST", RUH: "MIDDLE_EAST", JED: "MIDDLE_EAST",
  MED: "MIDDLE_EAST", DMM: "MIDDLE_EAST", AQJ: "MIDDLE_EAST",
  KWI: "MIDDLE_EAST", BAH: "MIDDLE_EAST", MCT: "MIDDLE_EAST",
  SLL: "MIDDLE_EAST", ALP: "MIDDLE_EAST",
  // Levant
  AMM: "MIDDLE_EAST", BEY: "MIDDLE_EAST", TLV: "MIDDLE_EAST",
  DAM: "MIDDLE_EAST",
  // Iraq / Iran
  BGW: "MIDDLE_EAST", BSR: "MIDDLE_EAST", NJF: "MIDDLE_EAST",
  EBL: "MIDDLE_EAST", ISU: "MIDDLE_EAST",
  IKA: "MIDDLE_EAST", THR: "MIDDLE_EAST", MHD: "MIDDLE_EAST",
  TBZ: "MIDDLE_EAST", KER: "MIDDLE_EAST", AHZ: "MIDDLE_EAST",
  // Yemen
  SAH: "MIDDLE_EAST", ADE: "MIDDLE_EAST",
  // Pakistan (geopolitically Mid-East adjacent for award routing)
  KHI: "MIDDLE_EAST", LHE: "MIDDLE_EAST", ISB: "MIDDLE_EAST",
  PEW: "MIDDLE_EAST",

  // ── Asia ─────────────────────────────────────────────────────────────────
  // South Asia (India, Sri Lanka, Nepal, Bangladesh, Maldives)
  DEL: "ASIA", BOM: "ASIA", BLR: "ASIA", MAA: "ASIA",
  HYD: "ASIA", CCU: "ASIA", AMD: "ASIA", GOI: "ASIA",
  TRV: "ASIA", COK: "ASIA", PNQ: "ASIA", ATQ: "ASIA",
  CMB: "ASIA", MLE: "ASIA", KTM: "ASIA", DAC: "ASIA",
  CGP: "ASIA",
  // Southeast Asia
  SIN: "ASIA", KUL: "ASIA", BKK: "ASIA", DMK: "ASIA",
  HKT: "ASIA", CNX: "ASIA", HDY: "ASIA",
  SGN: "ASIA", HAN: "ASIA", DAD: "ASIA", HPH: "ASIA",
  RGN: "ASIA", MDL: "ASIA",
  MNL: "ASIA", CEB: "ASIA", DVO: "ASIA", KLO: "ASIA",
  CGK: "ASIA", SUB: "ASIA", DPS: "ASIA", UPG: "ASIA",
  // East Asia
  PVG: "ASIA", PEK: "ASIA", PKX: "ASIA", CAN: "ASIA",
  CTU: "ASIA", CKG: "ASIA", WUH: "ASIA", CSX: "ASIA",
  XIY: "ASIA", KMG: "ASIA", XMN: "ASIA", HGH: "ASIA",
  NKG: "ASIA", TSN: "ASIA", CGO: "ASIA", TAO: "ASIA",
  URC: "ASIA", HRB: "ASIA", SHE: "ASIA",
  HKG: "ASIA", MFM: "ASIA",
  TPE: "ASIA", TSA: "ASIA", KHH: "ASIA",
  NRT: "ASIA", HND: "ASIA", KIX: "ASIA", NGO: "ASIA",
  FUK: "ASIA", CTS: "ASIA", OKA: "ASIA",
  ICN: "ASIA", GMP: "ASIA", PUS: "ASIA",
  // Mongolia / Central Asia
  ULN: "ASIA", ALA: "ASIA", TSE: "ASIA",
  TAS: "ASIA", OSS: "ASIA", FRU: "ASIA",
  // Myanmar (Burma)
  RGN: "ASIA",

  // ── South America ─────────────────────────────────────────────────────────
  // Brazil
  GRU: "SOUTH_AMERICA", GIG: "SOUTH_AMERICA", BSB: "SOUTH_AMERICA",
  SSA: "SOUTH_AMERICA", FOR: "SOUTH_AMERICA", REC: "SOUTH_AMERICA",
  BEL: "SOUTH_AMERICA", MAO: "SOUTH_AMERICA", POA: "SOUTH_AMERICA",
  FLN: "SOUTH_AMERICA", CWB: "SOUTH_AMERICA", CNF: "SOUTH_AMERICA",
  NAT: "SOUTH_AMERICA", VCP: "SOUTH_AMERICA",
  // Argentina / Uruguay / Paraguay
  EZE: "SOUTH_AMERICA", AEP: "SOUTH_AMERICA", COR: "SOUTH_AMERICA",
  MDZ: "SOUTH_AMERICA", BRC: "SOUTH_AMERICA", IGR: "SOUTH_AMERICA",
  MVD: "SOUTH_AMERICA", ASU: "SOUTH_AMERICA",
  // Chile / Bolivia / Peru / Ecuador
  SCL: "SOUTH_AMERICA", PMC: "SOUTH_AMERICA",
  LPB: "SOUTH_AMERICA", VVI: "SOUTH_AMERICA",
  LIM: "SOUTH_AMERICA", CUZ: "SOUTH_AMERICA",
  UIO: "SOUTH_AMERICA", GYE: "SOUTH_AMERICA",
  // Colombia / Venezuela / Guyana / Suriname
  BOG: "SOUTH_AMERICA", MDE: "SOUTH_AMERICA", CTG: "SOUTH_AMERICA",
  CLO: "SOUTH_AMERICA", BAQ: "SOUTH_AMERICA",
  CCS: "SOUTH_AMERICA", MAR: "SOUTH_AMERICA",
  GEO: "SOUTH_AMERICA", PBM: "SOUTH_AMERICA",
};

export function getZone(code: string): Zone | null {
  return ZONE_MAP[code.toUpperCase()] ?? null;
}
