// lib/zones.ts

export type Zone =
  | "AFRICA_WEST"
  | "AFRICA_NORTH"
  | "AFRICA_EAST"
  | "AFRICA_SOUTH"
  | "EUROPE"
  | "NORTH_AMERICA"
  | "MIDDLE_EAST"
  | "ASIA"
  | "SOUTH_AMERICA";

const ZONE_MAP: Record<string, Zone> = {
  // Africa North
  CMN: "AFRICA_NORTH", TUN: "AFRICA_NORTH", ALG: "AFRICA_NORTH",
  ORN: "AFRICA_NORTH", RAK: "AFRICA_NORTH", FEZ: "AFRICA_NORTH",
  // Africa West
  DSS: "AFRICA_WEST", DKR: "AFRICA_WEST", ABJ: "AFRICA_WEST",
  ACC: "AFRICA_WEST", LOS: "AFRICA_WEST",
  OUA: "AFRICA_WEST", CKY: "AFRICA_WEST", BKO: "AFRICA_WEST",
  COO: "AFRICA_WEST",
  LFW: "AFRICA_WEST", OXB: "AFRICA_WEST", BJL: "AFRICA_WEST",
  FNA: "AFRICA_WEST", ABV: "AFRICA_WEST", PHC: "AFRICA_WEST",
  DLA: "AFRICA_WEST", NSI: "AFRICA_WEST", LBV: "AFRICA_WEST",
  BZV: "AFRICA_WEST", SSG: "AFRICA_WEST", MLW: "AFRICA_WEST",
  NIM: "AFRICA_WEST", NDJ: "AFRICA_WEST",
  // Africa East (includes Central Africa — DRC, Congo)
  NBO: "AFRICA_EAST", ADD: "AFRICA_EAST", DAR: "AFRICA_EAST",
  EBB: "AFRICA_EAST", KGL: "AFRICA_EAST", MGQ: "AFRICA_EAST",
  MBA: "AFRICA_EAST", ZNZ: "AFRICA_EAST", MYD: "AFRICA_EAST",
  DJI: "AFRICA_EAST", JUB: "AFRICA_EAST", KRT: "AFRICA_EAST",
  FIH: "AFRICA_EAST",
  // Africa South
  JNB: "AFRICA_SOUTH", CPT: "AFRICA_SOUTH", LUN: "AFRICA_SOUTH",
  HRE: "AFRICA_SOUTH", WDH: "AFRICA_SOUTH", MRU: "AFRICA_SOUTH",
  TNR: "AFRICA_SOUTH", BLZ: "AFRICA_SOUTH", GBE: "AFRICA_SOUTH",
  LAD: "AFRICA_SOUTH", MPM: "AFRICA_SOUTH",
  // Europe
  CDG: "EUROPE", LHR: "EUROPE", AMS: "EUROPE", FRA: "EUROPE",
  MAD: "EUROPE", LIS: "EUROPE", FCO: "EUROPE", BCN: "EUROPE",
  IST: "EUROPE", ZRH: "EUROPE", BRU: "EUROPE", VIE: "EUROPE",
  MXP: "EUROPE", LGW: "EUROPE", ORY: "EUROPE", MAN: "EUROPE",
  CPH: "EUROPE", OSL: "EUROPE", ARN: "EUROPE", HEL: "EUROPE",
  WAW: "EUROPE", PRG: "EUROPE", BUD: "EUROPE", ATH: "EUROPE",
  DUB: "EUROPE", EDI: "EUROPE", GVA: "EUROPE", LYN: "EUROPE",
  // North America
  JFK: "NORTH_AMERICA", LAX: "NORTH_AMERICA", MIA: "NORTH_AMERICA",
  ORD: "NORTH_AMERICA", SFO: "NORTH_AMERICA", BOS: "NORTH_AMERICA",
  YYZ: "NORTH_AMERICA", YUL: "NORTH_AMERICA", DFW: "NORTH_AMERICA",
  ATL: "NORTH_AMERICA", IAD: "NORTH_AMERICA", EWR: "NORTH_AMERICA",
  SEA: "NORTH_AMERICA", LAS: "NORTH_AMERICA", DEN: "NORTH_AMERICA",
  MSY: "NORTH_AMERICA", YVR: "NORTH_AMERICA",
  // Middle East
  DXB: "MIDDLE_EAST", DOH: "MIDDLE_EAST", CAI: "MIDDLE_EAST",
  AMM: "MIDDLE_EAST", RUH: "MIDDLE_EAST", AUH: "MIDDLE_EAST",
  BEY: "MIDDLE_EAST", KWI: "MIDDLE_EAST", BAH: "MIDDLE_EAST",
  MCT: "MIDDLE_EAST", TLV: "MIDDLE_EAST", JED: "MIDDLE_EAST",
  // Asia
  SIN: "ASIA", HKG: "ASIA", NRT: "ASIA", ICN: "ASIA",
  BKK: "ASIA", KUL: "ASIA", PVG: "ASIA", DEL: "ASIA",
  BOM: "ASIA", PEK: "ASIA", CGK: "ASIA", MNL: "ASIA",
  CAN: "ASIA", TPE: "ASIA", HND: "ASIA", KIX: "ASIA",
  // South America
  GRU: "SOUTH_AMERICA", EZE: "SOUTH_AMERICA", BOG: "SOUTH_AMERICA",
  LIM: "SOUTH_AMERICA", SCL: "SOUTH_AMERICA", GIG: "SOUTH_AMERICA",
  CCS: "SOUTH_AMERICA", UIO: "SOUTH_AMERICA", MVD: "SOUTH_AMERICA",
};

export function getZone(code: string): Zone | null {
  return ZONE_MAP[code.toUpperCase()] ?? null;
}
